language: node_js
node_js:
  - "0.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install libcairo2-dev libfreetype6-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - cd .. && mv meteor-pdf.js pdf.js && cd pdf.js
  - "curl -L http://git.io/ejPSng | /bin/sh"
